import type { Metadata } from "next";
import { Michroma,  Orbitron} from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const michroma = Michroma({weight: '400', subsets: ['latin'], variable: '--font-michroma'});
const orbitron = Orbitron({subsets : ['latin'], variable: '--font-orbitron'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en" className={`${michroma.variable} ${orbitron.variable}`}>
      <body
      > <Header/>
        {children}
      </body>
    </html>
  );
}
